letitgo:
  name: sops64
  description: Sops wrapper that does base64 encoding and decoding for you.
  actions:
    - type: changelog
      file: CHANGELOG.md

    - type: githubrelease
      assets:
        - ./build/pkg/*

    - type: homebrew
      homepage: https://github.com/NoUseFreak/sops64
      url: https://github.com/NoUseFreak/sops64/releases/download/{{ .Version }}/darwin_amd64.zip
      version: "{{ .Version }}"
      tap:
        url: git@github.com:NoUseFreak/homebrew-brew.git
      test: system "#{bin}/{{ .Name }} -h"
