sudo: required
language: go
go:
- master
deploy:
  provider: releases
  api_key:
    secure: KcSJqdgL5laYDMXPBKclzQxdyFpwY9EiOyGpPN/eZ71krVsO4TAKk3DY40F+XCtN3ErmHgzVPnjXiwb/7k88PXDrZmanBTn2FWTMNUXAPJTkoT3c6Hy6qdVZ9uC/LHl00VYNdg9N1rFbRkaUdNWSfVwoqftX2c4Hpny3J4Vj8uNLYg705rhJyM2wfi3s+Vj376x9hGeOifr2HdMDErq8ROwJexS6rzE4oJZqezxlbFQRjgat4sslDQltuIE/07ctnfVr6eNBINpDG1DkYDYiiGZytXyjiCl8h5BYCgEZ2QV/UckH60+r/YeHWf/BUdWBdOsaSe8+XEsdKe3OnwdwwQd0KM+dj8Bkm/wnoAstSVBTAaQsKjbu69qtNM+1C5qR0LYaCcbz7HtzoLCrGKwfmImkk28e3/8j9MptKbUQ8kQVHoy4K9E5NE3DFiYICA6INiuDILb+bazcsn1Wd+eYEsBfDiKNmq1meAhag3rrATRaxkTC4r8v2d1j6iIYJ47R8MmcUu2LoZ5O2qitW+1DJLE4tQRnteMw33RN1XMkQXyjdWc//23fGiJfmgbeSPeGctbYxfSo0GH7HrEAk73E1b9x+E+d9SlepCLRGSYF5Rc4kmoAt0rr1qPmPa5Y2D+LIk0Li1fnMkprY8PK62kp1tBjKB1GutgoLJOLZV2HX6g=
  file_glob: true
  file: build/archive/*
  skip_cleanup: true
  on:
    repo: NoUseFreak/sops64
    tags: true
    branch: master
