language: go
go:
- stable
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/release.sh
  on:
    repo: NoUseFreak/sops64
    branch: master
    tags: true
env:
  global:
    secure: RboGcMUWjaX5RvsQtbkG6ZPaa9B6YKSZBLRvZGH1BZjdW9HwPrx+3nng9VWf3UUZWfn8N4047InWI5ChGZISo6dQHrCOUb5ctbQijFsiJ97k+1NWzy9K2aoRa+UG99Znga43tpPt6ie3RTS0EXWGe70qVqpnzQEz4orUUuSIhPFXreNj5NcdJZrkWDh9ka608No8cnEBfPRrHFtNrdHt2/Kf38Gb0yswHOql7FTQPqB3KodRHB+jmao+alDECKrjSArZpK0m0JrWy7w34PtHeYAj8drXGQaMKA561iB5FllDCuV1LvphOwSHChx2j+29igkdtwa4y1YgveicFmlsdan8rw5ZzwIWGnQI3dTwySXb48ATfvrlpo/fcfxJ2j1qzlhVWX1hWZHO2DHmsCNw4CL/pXHITVI+iifG/xSBMD/UkJkv1JWZEeGRnIVH04EL7MQitOfad28rGkB8Vk/S5DBuyQpqUtoSxteXxKXtKgOfENHgtKz/KFu7ZiIPnpM8fcvMSDgMP9fdqNfSW6C5j8mtd3JofiQFtDGdbO3nPHaPmA11osc+yjrDuURYM9WvEBx8IrCN/L6WKIsK2tIo4jcb5zA/+AqS5Fe2JZuzKJS/fXTB5UV8XKoUcjbGhm8nMdMDj3AplGh8XF5+p6xKlD8dswSOrbdUrlCT9C0j/IY=
